CREATE TABLE IF NOT EXISTS "users" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"email" VARCHAR(200) NOT NULL UNIQUE,
"password" VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS urls (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "original_url" VARCHAR(300) NOT NULL,
    "short_url" VARCHAR(300),
    "clicks" INTEGER NOT NULL DEFAULT 0,
    "user_id" INTEGER DEFAULT 0,
    "access" INTEGER
);